name: CI/CD with Vercel

on:
  push:
    branches:
      - '**'
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npm run lint:check

  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        ports: [5432:5432]
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npm run test:ci
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/testdb

  build:
    runs-on: ubuntu-latest
    # needs: [lint, test ,build] # build chỉ chạy khi lint + test pass
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npm run build

  preview-deploy:
    runs-on: ubuntu-latest
    needs: [lint, test ,build] 
    if: github.ref != 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npx vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - run: npm ci
      - run: |
          echo "Deploying PREVIEW for branch ${{ github.ref }}"
          npx vercel --token=${{ secrets.VERCEL_TOKEN }} --yes

  production-deploy:
    runs-on: ubuntu-latest
    needs: [lint, test ,build] 
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npx vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - run: npm ci
      - run: |
          echo "🚀🚀🚀 Deploying PRODUCTION"
          npx vercel --prod --token=${{ secrets.VERCEL_TOKEN }} --yes
