name: Test
on:
  workflow_call:

jobs:
  test:
    name: Setup environment
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node.js environment
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run:
          npm ci

      - name: Test
        run: npm run test
